# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:   # ✅ aqui dentro do serviço db
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  api: # NOVO SERVIÇO: Nossa API Java
    build: . # Manda o Docker construir a imagem usando o Dockerfile neste diretório
    ports:
      - "8080:8080" # Porta da API
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanagerdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy # espera o DB estar pronto

volumes:
  postgres_data:
